## Dataset 

https://www.kaggle.com/datasets/lava18/google-play-store-apps

In [1]:
import pandas as pd
data= pd.read_csv('googleplaystore.csv')
data

                                                     App             Category  ...         Current Ver         Android Ver
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN  ...               1.0.0        4.0.3 and up
1                                    Coloring book moana       ART_AND_DESIGN  ...               2.0.0        4.0.3 and up
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN  ...               1.2.4        4.0.3 and up
3                                  Sketch - Draw & Paint       ART_AND_DESIGN  ...  Varies with device          4.2 and up
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN  ...                 1.1          4.4 and up
...                                                  ...                  ...  ...                 ...                 ...
10836                                   Sya9a Maroc - FR               FAMILY  ...                1.48          4.1 and up
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY  ...                 1.0          4.1 and up
10838                             Parkinson Exercices FR              MEDICAL  ...                 1.0          2.2 and up
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE  ...  Varies with device  Varies with device
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE  ...  Varies with device  Varies with device

[10841 rows x 13 columns]

In [2]:
data.head()

                                                 App        Category  ...         Current Ver   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN  ...               1.0.0  4.0.3 and up
1                                Coloring book moana  ART_AND_DESIGN  ...               2.0.0  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN  ...               1.2.4  4.0.3 and up
3                              Sketch - Draw & Paint  ART_AND_DESIGN  ...  Varies with device    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN  ...                 1.1    4.4 and up

[5 rows x 13 columns]

In [3]:
data.tail()

                                                 App             Category  ...         Current Ver         Android Ver
10836                               Sya9a Maroc - FR               FAMILY  ...                1.48          4.1 and up
10837               Fr. Mike Schmitz Audio Teachings               FAMILY  ...                 1.0          4.1 and up
10838                         Parkinson Exercices FR              MEDICAL  ...                 1.0          2.2 and up
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE  ...  Varies with device  Varies with device
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE  ...  Varies with device  Varies with device

[5 rows x 13 columns]

In [6]:
data.shape

(10841, 13)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [9]:
data.describe(include='all')

           App Category       Rating Reviews  ... Genres    Last Updated         Current Ver Android Ver
count    10841    10841  9367.000000   10841  ...  10841           10841               10833       10838
unique    9660       34          NaN    6002  ...    120            1378                2832          33
top     ROBLOX   FAMILY          NaN       0  ...  Tools  August 3, 2018  Varies with device  4.1 and up
freq         9     1972          NaN     596  ...    842             326                1459        2451
mean       NaN      NaN     4.193338     NaN  ...    NaN             NaN                 NaN         NaN
std        NaN      NaN     0.537431     NaN  ...    NaN             NaN                 NaN         NaN
min        NaN      NaN     1.000000     NaN  ...    NaN             NaN                 NaN         NaN
25%        NaN      NaN     4.000000     NaN  ...    NaN             NaN                 NaN         NaN
50%        NaN      NaN     4.300000     NaN  ...    NaN             NaN                 NaN         NaN
75%        NaN      NaN     4.500000     NaN  ...    NaN             NaN                 NaN         NaN
max        NaN      NaN    19.000000     NaN  ...    NaN             NaN                 NaN         NaN

[11 rows x 13 columns]

In [24]:
# Find total number of app titles that contain Astrology
data[data['App'].str.contains('Astrology',case=False)]

                                                     App   Category  ...         Current Ver         Android Ver
1570   Horoscopes – Daily Zodiac Horoscope and Astrology  LIFESTYLE  ...          5.2.4(881)        4.0.3 and up
1592              သိင်္ Astrology - Min Thein Kha BayDin  LIFESTYLE  ...               4.2.1        4.0.3 and up
10840      iHoroscope - 2018 Daily Horoscope & Astrology  LIFESTYLE  ...  Varies with device  Varies with device

[3 rows x 13 columns]

In [25]:
# find average app ratings
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [27]:
data['Rating'].mean()

4.193338315362443

In [28]:
# find total number of unique category
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [30]:
data['Category'].nunique()

34

In [32]:
# which category getting the higest average rating

data[['Category','Rating']]

                  Category  Rating
0           ART_AND_DESIGN     4.1
1           ART_AND_DESIGN     3.9
2           ART_AND_DESIGN     4.7
3           ART_AND_DESIGN     4.5
4           ART_AND_DESIGN     4.3
...                    ...     ...
10836               FAMILY     4.5
10837               FAMILY     5.0
10838              MEDICAL     NaN
10839  BOOKS_AND_REFERENCE     4.5
10840            LIFESTYLE     4.5

[10841 rows x 2 columns]

In [40]:
data.groupby('Category')['Rating'].mean().sort_values(ascending=False)

Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.389032
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.346067
PERSONALIZATION         4.335987
PARENTING               4.300000
GAME                    4.286326
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.277104
SHOPPING                4.259664
SOCIAL                  4.255598
WEATHER                 4.244000
SPORTS                  4.223511
PRODUCTIVITY            4.211396
HOUSE_AND_HOME          4.197368
FAMILY                  4.192272
PHOTOGRAPHY             4.192114
AUTO_AND_VEHICLES       4.190411
MEDICAL                 4.189143
LIBRARIES_AND_DEMO      4.178462
FOOD_AND_DRINK          4.166972
COMMUNICATION           4.158537
COMICS                  4.155172
NEWS_AND_MAGAZINES      4.132189
FINANCE                 4.131889
ENTERTAINMENT           4.126174
BUSINESS                4.121452
TRAVEL_AND_LOCAL        4.109292
LIFESTYLE               4.094904
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.970769
Name: Rating, dtype: float64

In [41]:
# find the total number of apps havin 5 star rating
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [45]:
sum(data['Rating']==5.0)

274

In [46]:
data[data['Rating']==5]

                                              App   Category  Rating  ...       Last Updated Current Ver   Android Ver
329                  Hojiboy Tojiboyev Life Hacks     COMICS     5.0  ...      June 26, 2018         2.0  4.0.3 and up
612                 American Girls Mobile Numbers     DATING     5.0  ...      July 17, 2018         3.0  4.0.3 and up
615                                  Awake Dating     DATING     5.0  ...      July 24, 2018       2.2.9    4.4 and up
633                         Spine- The dating app     DATING     5.0  ...      July 14, 2018         4.0  4.0.3 and up
636    Girls Live Talk - Free Text and Video Chat     DATING     5.0  ...     August 1, 2018         8.2  4.0.3 and up
...                                           ...        ...     ...  ...                ...         ...           ...
10721                           Mad Dash Fo' Cash       GAME     5.0  ...      June 19, 2017        2.5a    4.1 and up
10742                       GKPB FP Online Church  LIFESTYLE     5.0  ...  December 31, 2017       0.7.1    4.4 and up
10776                            Monster Ride Pro       GAME     5.0  ...      March 5, 2018         2.0    2.3 and up
10820                             Fr. Daoud Lamei     FAMILY     5.0  ...      June 27, 2018       3.8.0    4.1 and up
10837            Fr. Mike Schmitz Audio Teachings     FAMILY     5.0  ...       July 6, 2018         1.0    4.1 and up

[274 rows x 13 columns]

In [47]:
# find average value of reviews
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [52]:
data['Reviews'].astype('float')

ValueError: could not convert string to float: '3.0M'

In [54]:
sum(data['Reviews']=='3.0M')

1

In [55]:
data['Reviews']=data['Reviews'].replace('3.0M',3.0)

In [56]:
data['Reviews']=data['Reviews'].astype('float')

In [58]:
data['Reviews'].dtype

dtype('float64')

In [59]:
data['Reviews'].mean()

444111.9265750392

In [60]:
# find total number of free and paid apps 

data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [69]:
data[data['Price']!='0']

                                                 App            Category  ...  Current Ver  Android Ver
234    TurboScan: scan documents and receipts in PDF            BUSINESS  ...        1.5.2   4.0 and up
235                   Tiny Scanner Pro: PDF Doc Scan            BUSINESS  ...        3.4.6   3.0 and up
290    TurboScan: scan documents and receipts in PDF            BUSINESS  ...        1.5.2   4.0 and up
291                   Tiny Scanner Pro: PDF Doc Scan            BUSINESS  ...        3.4.6   3.0 and up
427                               Puffin Browser Pro       COMMUNICATION  ...  7.5.3.20547   4.1 and up
...                                              ...                 ...  ...          ...          ...
10735                                    FP VoiceBot              FAMILY  ...          1.2   2.1 and up
10760                                Fast Tract Diet  HEALTH_AND_FITNESS  ...        1.9.3   4.2 and up
10782                        Trine 2: Complete Story                GAME  ...         2.22   5.0 and up
10785                                   sugar, sugar              FAMILY  ...          2.7   2.3 and up
10798                           Word Search Tab 1 FR              FAMILY  ...          1.1   3.0 and up

[801 rows x 13 columns]

In [67]:
data.shape

(10841, 13)

In [68]:
10841-10040

801

In [71]:
data['Type'].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [72]:
data[data['Type']=='0']

                                           App Category  Rating  ...  Last Updated Current Ver Android Ver
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0  ...        1.0.19  4.0 and up         NaN

[1 rows x 13 columns]

In [73]:
# which app has maximum review
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [76]:
data['Reviews'].sort_values(ascending=False)

2544    78158306.0
3943    78128208.0
381     69119316.0
336     69119316.0
3904    69109672.0
           ...
9713           0.0
8495           0.0
6277           0.0
8489           0.0
5086           0.0
Name: Reviews, Length: 10841, dtype: float64

In [79]:
data[data['Reviews'].max()==data['Reviews']]

           App Category  Rating     Reviews  ...  Genres    Last Updated         Current Ver         Android Ver
2544  Facebook   SOCIAL     4.1  78158306.0  ...  Social  August 3, 2018  Varies with device  Varies with device

[1 rows x 13 columns]

In [78]:
data['Reviews'].describe()

count    1.084100e+04
mean     4.441119e+05
std      2.927629e+06
min      0.000000e+00
25%      3.800000e+01
50%      2.094000e+03
75%      5.476800e+04
max      7.815831e+07
Name: Reviews, dtype: float64

In [80]:
# display top 5 apps having higest reviews
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [99]:
data.iloc[data['Reviews'].sort_values(ascending=False).head().index]

                     App       Category  Rating  ...    Last Updated         Current Ver         Android Ver
2544            Facebook         SOCIAL     4.1  ...  August 3, 2018  Varies with device  Varies with device
3943            Facebook         SOCIAL     4.1  ...  August 3, 2018  Varies with device  Varies with device
381   WhatsApp Messenger  COMMUNICATION     4.4  ...  August 3, 2018  Varies with device  Varies with device
336   WhatsApp Messenger  COMMUNICATION     4.4  ...  August 3, 2018  Varies with device  Varies with device
3904  WhatsApp Messenger  COMMUNICATION     4.4  ...  August 3, 2018  Varies with device  Varies with device

[5 rows x 13 columns]

In [100]:
# find the average rating of free and paid apps

In [103]:
data.groupby('Type')['Rating'].mean()

Type
0       19.000000
Free     4.186203
Paid     4.266615
Name: Rating, dtype: float64

In [104]:
# dispaly Top 5 Apps Having maximum installs

In [105]:
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [107]:
data.head()

                                                 App        Category  ...         Current Ver   Android Ver
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN  ...               1.0.0  4.0.3 and up
1                                Coloring book moana  ART_AND_DESIGN  ...               2.0.0  4.0.3 and up
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN  ...               1.2.4  4.0.3 and up
3                              Sketch - Draw & Paint  ART_AND_DESIGN  ...  Varies with device    4.2 and up
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN  ...                 1.1    4.4 and up

[5 rows x 13 columns]

In [112]:
data.iloc[data['Installs'].sort_values(ascending=False).head(6).index]

                                               App            Category  ...         Current Ver         Android Ver
10472      Life Made WI-Fi Touchscreen Photo Frame                 1.9  ...          4.0 and up                 NaN
420    UC Browser - Fast Download Private & Secure       COMMUNICATION  ...         12.8.5.1121          4.0 and up
474                    LINE: Free Calls & Messages       COMMUNICATION  ...  Varies with device  Varies with device
3767                  Flipboard: News For Our Time  NEWS_AND_MAGAZINES  ...  Varies with device  Varies with device
3574                                   Cloud Print        PRODUCTIVITY  ...  Varies with device  Varies with device
3326                  Gboard - the Google Keyboard               TOOLS  ...  Varies with device  Varies with device

[6 rows x 13 columns]

In [113]:
data['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', 'Free'], dtype=object)

In [114]:
data['Installs'].dtype

dtype('O')

In [146]:
data['Installs_new']=data['Installs'].replace('Free','0')

In [168]:
data['Installs_new']=data['Installs'].str.replace('+','')

In [169]:
data['Installs_new']=data['Installs_new'].str.replace(',','')

In [170]:
data['Installs_new'].dtype

dtype('O')

In [171]:
data['Installs_new']

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs_new, Length: 10841, dtype: object

In [172]:
data

                                                     App             Category  ...         Android Ver  Installs_new
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN  ...        4.0.3 and up         10000
1                                    Coloring book moana       ART_AND_DESIGN  ...        4.0.3 and up        500000
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN  ...        4.0.3 and up       5000000
3                                  Sketch - Draw & Paint       ART_AND_DESIGN  ...          4.2 and up      50000000
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN  ...          4.4 and up        100000
...                                                  ...                  ...  ...                 ...           ...
10836                                   Sya9a Maroc - FR               FAMILY  ...          4.1 and up          5000
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY  ...          4.1 and up           100
10838                             Parkinson Exercices FR              MEDICAL  ...          2.2 and up          1000
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE  ...  Varies with device          1000
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE  ...  Varies with device      10000000

[10841 rows x 14 columns]

In [173]:
data['Installs_new'].astype(int)

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs_new, Length: 10841, dtype: int32

In [177]:
data.iloc[data['Installs_new'].sort_values(ascending=False).head(5).index]

                                                    App            Category  ...         Android Ver  Installs_new
7536  Security Master - Antivirus, VPN, AppLock, Boo...               TOOLS  ...  Varies with device     500000000
474                         LINE: Free Calls & Messages       COMMUNICATION  ...  Varies with device     500000000
5596                                     Samsung Health  HEALTH_AND_FITNESS  ...          5.0 and up     500000000
371               Google Duo - High Quality Video Calls       COMMUNICATION  ...          4.4 and up     500000000
3767                       Flipboard: News For Our Time  NEWS_AND_MAGAZINES  ...  Varies with device     500000000

[5 rows x 14 columns]