# CASE STUDY-1

### Get the data set from below link 
https://www.kaggle.com/datasets/kaggle/sf-salaries

#### Import dataset and display top 10 rows

In [ ]:
import pandas as pd

df=pd.read_csv('Salaries.csv')
df

In [24]:
df.head(n=10)

   Id        EmployeeName                                        JobTitle    BasePay  ...  Year Notes         Agency  Status
0   1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18  ...  2011   NaN  San Francisco     NaN
1   2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)  155966.02  ...  2011   NaN  San Francisco     NaN
2   3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)  212739.13  ...  2011   NaN  San Francisco     NaN
3   4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC    77916.0  ...  2011   NaN  San Francisco     NaN
4   5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   134401.6  ...  2011   NaN  San Francisco     NaN
5   6      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   118602.0  ...  2011   NaN  San Francisco     NaN
6   7           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01  ...  2011   NaN  San Francisco     NaN
7   8       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS  256576.96  ...  2011   NaN  San Francisco     NaN
8   9      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)  176932.64  ...  2011   NaN  San Francisco     NaN
9  10  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   285262.0  ...  2011   NaN  San Francisco     NaN

[10 rows x 13 columns]

#### Dispaly Bottom 10 rows

In [25]:
df.tail(n=10)

            Id      EmployeeName                      JobTitle       BasePay  ...  Year Notes         Agency  Status
148644  148645      Randy D Winn  Stationary Eng, Sewage Plant          0.00  ...  2014   NaN  San Francisco      PT
148645  148646  Carolyn A Wilson     Human Services Technician          0.00  ...  2014   NaN  San Francisco      PT
148646  148647      Not provided                  Not provided  Not Provided  ...  2014   NaN  San Francisco     NaN
148647  148648    Joann Anderson   Communications Dispatcher 2          0.00  ...  2014   NaN  San Francisco      PT
148648  148649       Leon Walker                     Custodian          0.00  ...  2014   NaN  San Francisco      PT
148649  148650     Roy I Tillery                     Custodian          0.00  ...  2014   NaN  San Francisco      PT
148650  148651      Not provided                  Not provided  Not Provided  ...  2014   NaN  San Francisco     NaN
148651  148652      Not provided                  Not provided  Not Provided  ...  2014   NaN  San Francisco     NaN
148652  148653      Not provided                  Not provided  Not Provided  ...  2014   NaN  San Francisco     NaN
148653  148654         Joe Lopez    Counselor, Log Cabin Ranch          0.00  ...  2014   NaN  San Francisco      PT

[10 rows x 13 columns]

#### dispaly rows and columns in data set

In [26]:
df.shape

(148654, 13)

In [27]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

#### Dispaly data types of all colums

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

####  find the null value count in each row

In [29]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [30]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

#### dropping the rows whic are not reuired for analysis

In [31]:
df.drop(['Id','Agency','Status','Notes'],axis=1, inplace=True)

In [32]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [33]:
df.isnull().sum()

EmployeeName            0
JobTitle                0
BasePay               605
OvertimePay             0
OtherPay                0
Benefits            36159
TotalPay                0
TotalPayBenefits        0
Year                    0
dtype: int64

In [37]:
df.head(10)

         EmployeeName                                        JobTitle    BasePay  ...   TotalPay TotalPayBenefits  Year
0      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18  ...  567595.43        567595.43  2011
1        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)  155966.02  ...  538909.28        538909.28  2011
2      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)  212739.13  ...  335279.91        335279.91  2011
3   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC    77916.0  ...  332343.61        332343.61  2011
4     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   134401.6  ...  326373.19        326373.19  2011
5      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   118602.0  ...  316285.74        316285.74  2011
6           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01  ...  315981.05        315981.05  2011
7       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS  256576.96  ...  307899.46        307899.46  2011
8      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)  176932.64  ...  303427.55        303427.55  2011
9  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   285262.0  ...  302377.73        302377.73  2011

[10 rows x 9 columns]

In [39]:
df.describe(include='all')

       EmployeeName          JobTitle   BasePay  OvertimePay  ...  Benefits       TotalPay  TotalPayBenefits           Year
count        148654            148654  148049.0     148654.0  ...  112495.0  148654.000000     148654.000000  148654.000000
unique       110811              2159  109900.0      66555.0  ...   99635.0            NaN               NaN            NaN
top       Kevin Lee  Transit Operator       0.0          0.0  ...       0.0            NaN               NaN            NaN
freq             13              7036     875.0      66103.0  ...    1053.0            NaN               NaN            NaN
mean            NaN               NaN       NaN          NaN  ...       NaN   74768.321972      93692.554811    2012.522643
std             NaN               NaN       NaN          NaN  ...       NaN   50517.005274      62793.533483       1.117538
min             NaN               NaN       NaN          NaN  ...       NaN    -618.130000       -618.130000    2011.000000
25%             NaN               NaN       NaN          NaN  ...       NaN   36168.995000      44065.650000    2012.000000
50%             NaN               NaN       NaN          NaN  ...       NaN   71426.610000      92404.090000    2013.000000
75%             NaN               NaN       NaN          NaN  ...       NaN  105839.135000     132876.450000    2014.000000
max             NaN               NaN       NaN          NaN  ...       NaN  567595.430000     567595.430000    2014.000000

[11 rows x 9 columns]

In [40]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

#### count top 5 most occured employeee

In [43]:
df['EmployeeName'].value_counts().head(5)

EmployeeName
Kevin Lee       13
Richard Lee     11
Steven Lee      11
William Wong    11
Stanley Lee      9
Name: count, dtype: int64

#### Uniqure values in jobtitile

In [47]:
df['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

#### number of unique values in jobtitle

In [48]:
df['JobTitle'].nunique()

2159

#### find all the details of employees whoes title cotains 'Captain'

In [59]:
df[df['JobTitle'].str.contains('Captain',case=False)]

              EmployeeName                               JobTitle    BasePay  ...   TotalPay TotalPayBenefits  Year
1             GARY JIMENEZ        CAPTAIN III (POLICE DEPARTMENT)  155966.02  ...  538909.28        538909.28  2011
2           ALBERT PARDINI        CAPTAIN III (POLICE DEPARTMENT)  212739.13  ...  335279.91        335279.91  2011
11        PATRICIA JACKSON        CAPTAIN III (POLICE DEPARTMENT)    99722.0  ...  297608.92        297608.92  2011
17          SEBASTIAN WONG  CAPTAIN, EMERGENCYCY MEDICAL SERVICES  140546.87  ...  278569.21        278569.21  2011
22           GEORGE GARCIA              CAPTAIN, FIRE SUPPRESSION  140546.88  ...  273702.71        273702.71  2011
...                    ...                                    ...        ...  ...        ...              ...   ...
116604   Gregory L Stewart              Captain, Fire Suppression   73355.21  ...  141790.12        167398.89  2014
120867     Michael J Moran                              Captain 3     7660.0  ...  135716.45        137905.96  2014
122361  Michael V Rolovich              Captain, Fire Suppression        0.0  ...  130320.75        130320.75  2014
126588    Stephen M Tittel                              Captain 3   68491.89  ...   92213.80        111234.59  2014
132232     Jeanne M Seyler              Captain, Fire Suppression   61039.43  ...   70873.02         90986.78  2014

[552 rows x 9 columns]

In [69]:
df['JobTitle'].str.contains('Captain',case=False).sum()

552

In [70]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [72]:
df['JobTitle'].str.contains('fire',case=False).sum()

5879

#### job title contains fire case sensitive

In [74]:
df[df['JobTitle'].str.contains('fire',case=False)]

              EmployeeName                                          JobTitle  ... TotalPayBenefits  Year
4          PATRICK GARDNER      DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  ...        326373.19  2011
6                ALSON LEE                BATTALION CHIEF, (FIRE DEPARTMENT)  ...        315981.05  2011
8           MICHAEL MORRIS                BATTALION CHIEF, (FIRE DEPARTMENT)  ...        303427.55  2011
9       JOANNE HAYES-WHITE            CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  ...        302377.73  2011
10           ARTHUR KENNEY  ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  ...        299494.17  2011
...                    ...                                               ...  ...              ...   ...
145956    Kenneth C Farris                                       Firefighter  ...          4645.56  2014
147556       Edward A Dunn                                       Firefighter  ...          1581.80  2014
148021      Kari A Johnson                                       Firefighter  ...           832.10  2014
148209        Sheryl K Lee                                       Firefighter  ...           554.73  2014
148554     Lawrence F Gatt                             Fire Alarm Dispatcher  ...            74.06  2014

[5879 rows x 9 columns]

In [82]:
df[df['JobTitle'].str.contains('fire',case=False)]['EmployeeName']

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: object

In [83]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year',
       'Fire_department_Ename', 'Department'],
      dtype='object')

In [93]:
# df['BasePay']=df['BasePay'].astype(float)
df['BasePay']=df['BasePay'].str.replace('Not Provided','0')
df['BasePay']=df['BasePay'].astype(float)

In [96]:
df['BasePay'].describe()

count    17582.000000
mean     29219.866678
std      22187.012035
min          0.000000
25%       7797.152500
50%      25336.765000
75%      51515.000000
max      92945.870000
Name: BasePay, dtype: float64

In [97]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year',
       'Fire_department_Ename', 'Department'],
      dtype='object')

In [101]:
import numpy as np
df['EmployeeName']=df['EmployeeName'].replace('Not provided',np.nan)

In [105]:
df.replace('Not provided', np.nan, inplace=True)

In [106]:
df

             EmployeeName  ...                                        Department
0          NATHANIEL FORD  ...  [GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY]
1            GARY JIMENEZ  ...                [CAPTAIN III , POLICE DEPARTMENT)]
2          ALBERT PARDINI  ...                [CAPTAIN III , POLICE DEPARTMENT)]
3       CHRISTOPHER CHONG  ...            [WIRE ROPE CABLE MAINTENANCE MECHANIC]
4         PATRICK GARDNER  ...   [DEPUTY CHIEF OF DEPARTMENT,, FIRE DEPARTMENT)]
...                   ...  ...                                               ...
148649      Roy I Tillery  ...                                       [Custodian]
148650                NaN  ...                                    [Not provided]
148651                NaN  ...                                    [Not provided]
148652                NaN  ...                                    [Not provided]
148653          Joe Lopez  ...                      [Counselor, Log Cabin Ranch]

[148654 rows x 11 columns]

In [111]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year',
       'Fire_department_Ename', 'Department'],
      dtype='object')

In [114]:
df.drop(['Fire_department_Ename'], axis=1)

             EmployeeName  ...                                        Department
0          NATHANIEL FORD  ...  [GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY]
1            GARY JIMENEZ  ...                [CAPTAIN III , POLICE DEPARTMENT)]
2          ALBERT PARDINI  ...                [CAPTAIN III , POLICE DEPARTMENT)]
3       CHRISTOPHER CHONG  ...            [WIRE ROPE CABLE MAINTENANCE MECHANIC]
4         PATRICK GARDNER  ...   [DEPUTY CHIEF OF DEPARTMENT,, FIRE DEPARTMENT)]
...                   ...  ...                                               ...
148649      Roy I Tillery  ...                                       [Custodian]
148650                NaN  ...                                    [Not provided]
148651                NaN  ...                                    [Not provided]
148652                NaN  ...                                    [Not provided]
148653          Joe Lopez  ...                      [Counselor, Log Cabin Ranch]

[148654 rows x 10 columns]

In [123]:
df[df.isnull().sum(axis=1)==5]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Fire_department_Ename, Department]
Index: []

In [124]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year',
       'Fire_department_Ename', 'Department'],
      dtype='object')

#### find employeee "Albert Pardini" and his tjob title

In [127]:
df[df['EmployeeName']=='Albert Pardini']['JobTitle']

36519    Captain 3
Name: JobTitle, dtype: object

In [131]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year',
       'Fire_department_Ename', 'Department'],
      dtype='object')

In [133]:
df[df['EmployeeName']=='Albert Pardini']['TotalPayBenefits']

36519    253995.29
Name: TotalPayBenefits, dtype: float64

In [145]:
df[df['BasePay'].max()==df['BasePay']]['EmployeeName']

131453    Timothy J Lee
Name: EmployeeName, dtype: object

In [146]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year',
       'Fire_department_Ename', 'Department'],
      dtype='object')

In [148]:
df['EmployeeName'].nunique()

110810

In [166]:
r=df.groupby('Year')

for i in  r:
    print(i)

(2011,              EmployeeName  ...                                        Department
0          NATHANIEL FORD  ...  [GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY]
1            GARY JIMENEZ  ...                [CAPTAIN III , POLICE DEPARTMENT)]
2          ALBERT PARDINI  ...                [CAPTAIN III , POLICE DEPARTMENT)]
3       CHRISTOPHER CHONG  ...            [WIRE ROPE CABLE MAINTENANCE MECHANIC]
4         PATRICK GARDNER  ...   [DEPUTY CHIEF OF DEPARTMENT,, FIRE DEPARTMENT)]
...                   ...  ...                                               ...
36154       SERENA HUGHES  ...              [SWIMMING INSTRUCTOR/POOL LIFEGUARD]
36155        JOE BROWN JR  ...                                [TRANSIT OPERATOR]
36156      PAULETTE ADAMS  ...      [STATIONARY ENGINEER, WATER TREATMENT PLANT]
36157       KAUKAB MOHSIN  ...                                [TRANSIT OPERATOR]
36158  JOSEPHINE MCCREARY  ...                                      [MANAGER IV]

[36159 rows x 11 columns])
(2012,              EmployeeName                      JobTitle  ...  Fire_department_Ename                      Department
36159      Gary Altenberg  Lieutenant, Fire Suppression  ...                   True  [Lieutenant, Fire Suppression]
36160        Gregory Suhr               Chief of Police  ...                  False               [Chief of Police]
36161          Khoa Trinh   Electronic Maintenance Tech  ...                  False   [Electronic Maintenance Tech]
36162  Joanne Hayes-White        Chief, Fire Department  ...                   True        [Chief, Fire Department]
36163   Frederick Binkley     EMT/Paramedic/Firefighter  ...                   True     [EMT/Paramedic/Firefighter]
...                   ...                           ...  ...                    ...                             ...
72920    Charles Williams                  Junior Clerk  ...                  False                  [Junior Clerk]
72921        John Carajan               General Laborer  ...                  False               [General Laborer]
72922         John Draper                         Clerk  ...                  False                         [Clerk]
72923        Cherise Wong                 Special Nurse  ...                  False                 [Special Nurse]
72924        Donald Clark              Transit Operator  ...                  False              [Transit Operator]

[36766 rows x 11 columns])
(2013,                 EmployeeName                        JobTitle  ...  Fire_department_Ename                        Department
72925         Gregory P Suhr                 Chief of Police  ...                  False                 [Chief of Police]
72926   Joanne M Hayes-White          Chief, Fire Department  ...                   True          [Chief, Fire Department]
72927            Samson  Lai  Battalion Chief, Fire Suppress  ...                   True  [Battalion Chief, Fire Suppress]
72928        Ellen G Moffatt               Asst Med Examiner  ...                  False               [Asst Med Examiner]
72929          Robert L Shaw    Dep Dir for Investments, Ret  ...                  False    [Dep Dir for Investments, Ret]
...                      ...                             ...  ...                    ...                               ...
110526        Arthur L Curry         PS Aide Health Services  ...                  False         [PS Aide Health Services]
110527         Nereida  Vega                    Senior Clerk  ...                  False                    [Senior Clerk]
110528      Timothy E Gibson                Police Officer 3  ...                  False                [Police Officer 3]
110529        Mark E Laherty                Police Officer 3  ...                  False                [Police Officer 3]
110530         David P Kucia                Police Officer 3  ...                  False                [Police Officer 3]

[37606 rows x 11 columns])
(2014,                 EmployeeName                    JobTitle  ...  Fire_department_Ename                    Department
110531           David Shinn              Deputy Chief 3  ...                  False              [Deputy Chief 3]
110532            Amy P Hart           Asst Med Examiner  ...                  False           [Asst Med Examiner]
110533  William J Coaker Jr.    Chief Investment Officer  ...                  False    [Chief Investment Officer]
110534        Gregory P Suhr             Chief of Police  ...                  False             [Chief of Police]
110535  Joanne M Hayes-White      Chief, Fire Department  ...                   True      [Chief, Fire Department]
...                      ...                         ...  ...                    ...                           ...
148649         Roy I Tillery                   Custodian  ...                  False                   [Custodian]
148650                   NaN                         NaN  ...                  False                [Not provided]
148651                   NaN                         NaN  ...                  False                [Not provided]
148652                   NaN                         NaN  ...                  False                [Not provided]
148653             Joe Lopez  Counselor, Log Cabin Ranch  ...                  False  [Counselor, Log Cabin Ranch]

[38123 rows x 11 columns])

In [170]:
df.groupby('Year').get_group(2011)

             EmployeeName  ...                                        Department
0          NATHANIEL FORD  ...  [GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY]
1            GARY JIMENEZ  ...                [CAPTAIN III , POLICE DEPARTMENT)]
2          ALBERT PARDINI  ...                [CAPTAIN III , POLICE DEPARTMENT)]
3       CHRISTOPHER CHONG  ...            [WIRE ROPE CABLE MAINTENANCE MECHANIC]
4         PATRICK GARDNER  ...   [DEPUTY CHIEF OF DEPARTMENT,, FIRE DEPARTMENT)]
...                   ...  ...                                               ...
36154       SERENA HUGHES  ...              [SWIMMING INSTRUCTOR/POOL LIFEGUARD]
36155        JOE BROWN JR  ...                                [TRANSIT OPERATOR]
36156      PAULETTE ADAMS  ...      [STATIONARY ENGINEER, WATER TREATMENT PLANT]
36157       KAUKAB MOHSIN  ...                                [TRANSIT OPERATOR]
36158  JOSEPHINE MCCREARY  ...                                      [MANAGER IV]

[36159 rows x 11 columns]

#### find mean of bsepay of all employees per year

In [174]:
grpfunc=df.groupby('Year')
grpfunc['BasePay'].aggregate(np.mean)

Year
2011             NaN
2012             NaN
2013             NaN
2014    29219.866678
Name: BasePay, dtype: float64

In [175]:
df['BasePay'].dtype

dtype('float64')

In [176]:
df.groupby('Year')['BasePay'].mean()

Year
2011             NaN
2012             NaN
2013             NaN
2014    29219.866678
Name: BasePay, dtype: float64

In [181]:
grp=df.groupby('JobTitle')

grp['BasePay'].aggregate(np.mean)

JobTitle
ACCOUNT CLERK                                              NaN
ACCOUNTANT                                                 NaN
ACCOUNTANT INTERN                                          NaN
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                              NaN
                                                      ...
X-RAY LABORATORY AIDE                                      NaN
X-Ray Laboratory Aide                             34056.416818
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS             NaN
Youth Comm Advisor                                32417.420000
ZOO CURATOR                                                NaN
Name: BasePay, Length: 2158, dtype: float64

In [182]:
grp=df.groupby('JobTitle').get_group('ACCOUNTANT')

grp['BasePay'].aggregate(np.mean)

nan

In [183]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year',
       'Fire_department_Ename', 'Department'],
      dtype='object')

#### unique values in jobtitle display top 5

In [211]:
df['JobTitle'].value_counts().head(n=5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [209]:
grp=df.groupby('JobTitle')
for i, y in grp:
    print(i)
    print(y.shape)

ACCOUNT CLERK
(83, 11)
ACCOUNTANT
(5, 11)
ACCOUNTANT INTERN
(48, 11)
ACPO,JuvP, Juv Prob (SFERS)
(1, 11)
ACUPUNCTURIST
(1, 11)
ADMINISTRATIVE ANALYST
(93, 11)
ADMINISTRATIVE ANALYST II
(2, 11)
ADMINISTRATIVE ANALYST III
(2, 11)
ADMINISTRATIVE ENGINEER
(10, 11)
ADMINISTRATIVE SERVICES MANAGER
(3, 11)
ADMINISTRATOR, SFGH MEDICAL CENTER
(1, 11)
AFFIRMATIVE ACTION SPECIALIST
(6, 11)
AGRICULTURAL INSPECTOR
(2, 11)
AIRPORT ASSISTANT DEPUTY DIRECTOR, BUSINESS ADMINI
(1, 11)
AIRPORT ASSISTANT DEPUTY DIRECTOR, OPERATIONS
(1, 11)
AIRPORT COMMUNICATIONS OPERATOR
(27, 11)
AIRPORT COMMUNICATIONS SUPERVISOR
(2, 11)
AIRPORT ECONOMIC PLANNER
(13, 11)
AIRPORT ELECTRICIAN
(17, 11)
AIRPORT ELECTRICIAN SUPERVISOR
(2, 11)
AIRPORT EMERGENCY PLANNING COORDINATOR
(2, 11)
AIRPORT MECHANICAL MAINTENANCE SUPERVISOR
(1, 11)
AIRPORT NOISE ABATEMENT SPECIALIST
(2, 11)
AIRPORT OPERATIONS SUPERVISOR
(12, 11)
AIRPORT POLICE SERVICES AIDE
(187, 11)
AIRPORT PROPERTY SPECIALIST I
(13, 11)
AIRPORT SAFETY OFFICER
(40, 11)
ANESTHETIST
(25, 11)
ANIMAL CARE ASSISTANT SUPERVISOR
(1, 11)
ANIMAL CARE ATTENDANT
(14, 11)
ANIMAL CARE SUPERVISOR
(1, 11)
ANIMAL CONTROL OFFICER
(13, 11)
ANIMAL HEALTH TECHNICIAN
(3, 11)
ANIMAL KEEPER
(4, 11)
APPRENTICE GARDENER
(11, 11)
APPRENTICE STATIONARY ENGINEER
(12, 11)
APPRENTICE STATIONARY ENGINEER, SEWAGE PLANT
(13, 11)
APPRENTICE STATIONARY ENGINEER,WATER TREATMENT PLN
(6, 11)
ARCHITECT
(15, 11)
ARCHITECTURAL ADMINISTRATOR
(4, 11)
ARCHITECTURAL ASSISTANT  I
(2, 11)
ARCHITECTURAL ASSISTANT II
(19, 11)
ARCHITECTURAL ASSOCIATE  I
(13, 11)
ARCHITECTURAL ASSOCIATE II
(20, 11)
AREA SUPERVISOR, PARKS, SQUARES AND FACILITIES
(1, 11)
ARTS PROGRAM ASSISTANT
(11, 11)
ASPHALT FINISHER
(10, 11)
ASPHALT FINISHER SUPERVISOR I
(8, 11)
ASPHALT PLANT SUPERVISOR I
(1, 11)
ASPHALT WORKER
(26, 11)
ASR Senior Office Specialist
(60, 11)
ASR-Office Assistant
(41, 11)
ASSESSMENT CLERK
(36, 11)
ASSESSOR
(1, 11)
ASSISTANT CHIEF ATTORNEY I
(23, 11)
ASSISTANT CHIEF ATTORNEY II
(5, 11)
ASSISTANT CHIEF DISTRICT ATTORNEY'S INVESTIGATOR
(4, 11)
ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
(3, 11)
ASSISTANT CHIEF VICTIM/WITNESS INVESTIGATOR
(5, 11)
ASSISTANT CLERK, BOARD OF SUPERVISORS
(5, 11)
ASSISTANT CONSTRUCTION INSPECTOR
(7, 11)
ASSISTANT COOK
(6, 11)
ASSISTANT COUNSELOR
(4, 11)
ASSISTANT COURT REPORTER COORDINATOR
(1, 11)
ASSISTANT DEPUTY CHIEF II
(5, 11)
ASSISTANT DEPUTY DIRECTOR, PORT
(2, 11)
ASSISTANT DIRECTOR OF CLINICAL SERVICES I
(1, 11)
ASSISTANT DIRECTOR OF CLINICAL SERVICES II
(1, 11)
ASSISTANT DIRECTOR, JUVENILE HALL
(1, 11)
ASSISTANT DIRECTOR, LOG CABIN RANCH
(1, 11)
ASSISTANT ELECTRONIC MAINTENANCE TECHNICIAN
(11, 11)
ASSISTANT ENGINEER
(146, 11)
ASSISTANT FORENSIC TOXICOLOGIST I
(6, 11)
ASSISTANT GENERAL SERVICES MANAGER
(6, 11)
ASSISTANT HEALTH EDUCATOR
(8, 11)
ASSISTANT INDUSTRIAL HYGIENIST
(1, 11)
ASSISTANT INSPECTOR (POLICE DEPARTMENT)
(1, 11)
ASSISTANT INSPECTOR II (POLICE DEPARTMENT)
(10, 11)
ASSISTANT INSPECTOR III (POLICE DEPARTMENT)
(9, 11)
ASSISTANT LAW LIBRARIAN
(1, 11)
ASSISTANT MATERIALS COORDINATOR
(12, 11)
ASSISTANT MEDICAL EXAMINER
(5, 11)
ASSISTANT POWER HOUSE OPERATOR
(2, 11)
ASSISTANT PURCHASER
(23, 11)
ASSISTANT RECREATION DIRECTOR
(2, 11)
ASSISTANT RECREATION SUPERVISOR
(1, 11)
ASSISTANT RENTAL MANAGER, PORT
(7, 11)
ASSISTANT RETIREMENT ANALYST
(26, 11)
ASSISTANT SHERIFF
(2, 11)
ASSISTANT STOREKEEPER
(15, 11)
ASSISTANT SUPERINTENDENT RECREATION
(1, 11)
ASSISTANT TO THE DIRECTOR, PUBLIC AFFAIRS       RS
(1, 11)
ASSOCIATE AFFIRMATIVE ACTION COORDINATOR
(8, 11)
ASSOCIATE AUDITOR
(17, 11)
ASSOCIATE ENGINEER
(148, 11)
ASSOCIATE HUMAN RESOURCES ANALYST
(1, 11)
ASSOCIATE MUSEUM CONSERVATOR, ASIAN ART MUSEUM
(1, 11)
ASSOCIATE MUSEUM REGISTRAR
(2, 11)
ASSOCIATE PERFORMANCE AUDITOR
(11, 11)
ASST. CHIEF PROBATION OFFICER-JUVENILE PROBATION
(1, 11)
ASST. CHIEF, BUREAU OF CLAIMS INVEST. & ADMIN
(1, 11)
ATTORNEY (CIVIL/CRIMINAL)
(377, 11)
ATTORNEY FOR THE PUBLIC ADMINISTRATOR
(1, 11)
ATTORNEY, TAX COLLECTOR
(2, 11)
AUDIOLOGIST
(1, 11)
AUDIOMETRIST
(2, 11)
AUTOMOTIVE BODY AND FENDER WORKER
(38, 11)
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I
(1, 11)
AUTOMOTIVE MACHINIST
(66, 11)
AUTOMOTIVE MACHINIST ASSISTANT SUPERVISOR
(8, 11)
AUTOMOTIVE MACHINIST SUPERVISOR I
(7, 11)
AUTOMOTIVE MECHANIC
(126, 11)
AUTOMOTIVE MECHANIC ASSISTANT SUPERVISOR
(11, 11)
AUTOMOTIVE MECHANIC SUPERVISOR I
(6, 11)
AUTOMOTIVE SERVICE WORKER
(110, 11)
AUTOMOTIVE SERVICE WORKER ASSISTANT SUPERVISOR
(4, 11)
AUTOMOTIVE TRANSIT SHOP SUPERVISOR I
(5, 11)
Account Clerk
(268, 11)
Accountant I
(8, 11)
Accountant II
(226, 11)
Accountant III
(278, 11)
Accountant IV
(171, 11)
Accountant Intern
(60, 11)
Acupuncturist
(3, 11)
Adm, SFGH Medical Center
(3, 11)
Admin Analyst 3
(6, 11)
Admin Hearing Examiner
(31, 11)
Administrative Analyst
(368, 11)
Administrative Analyst I
(2, 11)
Administrative Analyst II
(3, 11)
Administrative Engineer
(29, 11)
Administrative Hearing Sup
(1, 11)
Administrative Services Mgr
(11, 11)
Administrator, DPH
(2, 11)
Admission Attendant
(164, 11)
Agricultural Inspector
(6, 11)
Airport Communications Disp
(85, 11)
Airport Communications Officer
(2, 11)
Airport Economic Planner
(38, 11)
Airport Electrician
(50, 11)
Airport Electrician Supervisor
(6, 11)
Airport Emerg Planning Coord
(9, 11)
Airport Mechanical Maint Sprv
(2, 11)
Airport Noise Abatement Spec
(8, 11)
Airport Operations Supervisor
(39, 11)
Airport Property Specialist 1
(36, 11)
Airport Safety Officer
(128, 11)
Airports Communications Sprv
(6, 11)
Anesthetist
(66, 11)
Animal Care Asst Supv
(3, 11)
Animal Care Attendant
(46, 11)
Animal Care Supervisor
(2, 11)
Animal Control Officer
(38, 11)
Animal Control Supervisor
(3, 11)
Animal Health Technician
(8, 11)
Animal Keeper
(12, 11)
Apprentice Cement Mason I
(4, 11)
Apprentice Gardener
(76, 11)
Apprentice Stationary Engineer
(27, 11)
Aprntc Statnry Eng, Sew Plant
(40, 11)
AprntcStatnry Eng,WtrTreatPlnt
(11, 11)
Aquatics Facility Asst Supv
(27, 11)
Aquatics Facility Supervisor
(23, 11)
Arborist Technician
(75, 11)
Arborist Technician Supervisor
(23, 11)
Arborist Technician Supv II
(3, 11)
Architect
(40, 11)
Architectural Administrator
(11, 11)
Architectural Assistant 1
(35, 11)
Architectural Assistant 2
(50, 11)
Architectural Associate 1
(36, 11)
Architectural Associate 2
(54, 11)
Area Sprv Parks, Squares & Fac
(3, 11)
Arts Program Assistant
(33, 11)
Asphalt Finisher
(36, 11)
Asphalt Finisher Supervisor 1
(27, 11)
Asphalt Plant Supervisor 1
(3, 11)
Asphalt Worker
(59, 11)
Assessment Clerk
(27, 11)
Assessor
(3, 11)
Assessor-Recorder Office Spec
(33, 11)
Assistant Chief Attorney 1
(71, 11)
Assistant Chief Attorney 2
(18, 11)
Assistant Const Inspector
(54, 11)
Assistant Cook
(17, 11)
Assistant Counselor
(10, 11)
Assistant Deputy Chief 2
(11, 11)
Assistant Director, Probate
(2, 11)
Assistant Health Educator
(24, 11)
Assistant Industrial Hygienist
(3, 11)
Assistant Inspector
(2, 11)
Assistant Inspector 2
(5, 11)
Assistant Inspector 3
(17, 11)
Assistant Law Librarian
(4, 11)
Assistant Power House Operator
(3, 11)
Assistant Purchaser
(72, 11)
Assistant Recreation Director
(22, 11)
Assistant Retirement Analyst
(65, 11)
Assistant Sheriff
(4, 11)
Assistant Storekeeper
(66, 11)
Assoc Engineer
(507, 11)
Assoc Musm Cnsrvt, AAM
(3, 11)
Associate Museum Registrar
(11, 11)
Asst Chf Dist Atty's Invstgtor
(15, 11)
Asst Chf Prob Ofc, Juv Prob
(1, 11)
Asst Chf Victim/Wit Invstgtor
(19, 11)
Asst Chf of Dept (Fire Dept)
(18, 11)
Asst Chf, Bur Clm Invest&Admin
(2, 11)
Asst Clk, Board of Supervisors
(14, 11)
Asst Dir Clinical Svcs 2
(1, 11)
Asst Dir of Clinical Svcs 1
(3, 11)
Asst Dir, Log Cabin Rnch
(3, 11)
Asst Director, Juvenile Hall
(3, 11)
Asst Electronic Main Tech
(18, 11)
Asst Engr
(461, 11)
Asst Forensic Toxicologist 1
(18, 11)
Asst General Services Manager
(17, 11)
Asst Materials Coordinator
(33, 11)
Asst Med Examiner
(12, 11)
Asst Superintendent Rec
(3, 11)
Asst.Dep.Dir., Port
(6, 11)
Attorney (Civil/Criminal)
(1126, 11)
Attorney, Tax Collector
(3, 11)
Audiologist
(4, 11)
Audiometrist
(2, 11)
Auditor I
(18, 11)
Auditor II
(42, 11)
Auditor III
(29, 11)
Auto Body & Fender Wrk Sprv 1
(3, 11)
Auto Body&Fender Wrk Asst Sprv
(1, 11)
Auto Machinist Asst Sprv
(21, 11)
Auto Svc Wrk Asst Sprv
(11, 11)
Automotive Body & Fender Wrk
(106, 11)
Automotive Machinist
(216, 11)
Automotive Machinist Sprv 1
(28, 11)
Automotive Mechanic
(436, 11)
Automotive Mechanic Asst Sprv
(36, 11)
Automotive Mechanic Sprv 1
(21, 11)
Automotive Service Worker
(340, 11)
Automotive Trnst Shop Sprv 1
(19, 11)
BACTERIOLOGICAL LABORATORY ASSISTANT
(8, 11)
BAKER
(1, 11)
BARBER
(1, 11)
BATTALION CHIEF, (FIRE DEPARTMENT)
(45, 11)
BEAUTICIAN
(3, 11)
BENEFITS ANALYST
(14, 11)
BENEFITS SUPERVISOR
(5, 11)
BENEFITS TECHNICIAN
(23, 11)
BIOLOGIST I/II
(23, 11)
BIOLOGIST III
(4, 11)
BOARD COMMISSION MEMBER, $200 PER MEETING
(7, 11)
BOARD SECRETARY - MUNICIPAL TRANSPORTATION AGENC
(1, 11)
BOARD/COMMISSION MEMBER, GROUP II
(43, 11)
BOARD/COMMISSION MEMBER, GROUP III
(33, 11)
BOARD/COMMISSION MEMBER, GROUP V
(56, 11)
BOARD/COMMISSION SECRETARY III
(2, 11)
BOOK REPAIRER
(3, 11)
BRAILLIST
(1, 11)
BRICKLAYER
(5, 11)
BUILDING AND GROUNDS PATROL OFFICER
(49, 11)
BUILDING INSPECTOR
(52, 11)
BUILDING PLANS ENGINEER
(2, 11)
BUILDING SERVICES TECHNICIAN
(1, 11)
BUILDINGS AND GROUNDS MAINTENANCE SUPERINTENDENT
(13, 11)
BUILDINGS AND GROUNDS MAINTENANCE SUPERVISOR
(6, 11)
Baker
(3, 11)
Barber
(7, 11)
Battalion Chief, Fire Suppress
(65, 11)
Battlion Chief, Fire Suppressi
(36, 11)
Bd/Comm Secretary 3
(3, 11)
BdComm Mbr, Grp2,M=$25/Mtg
(124, 11)
BdComm Mbr, Grp3,M=$50/Mtg
(116, 11)
BdComm Mbr, Grp5,M$100/Mo
(166, 11)
Beautician
(6, 11)
Benefits Analyst
(44, 11)
Benefits Supervisor
(18, 11)
Benefits Technician
(73, 11)
Biologist
(23, 11)
Biologist I/II
(42, 11)
Biologist III
(17, 11)
Bldg & Grounds Maint Sprv
(25, 11)
Bldg & Grounds Patrol Officer
(154, 11)
Bldgs & Grounds Maint Supt
(52, 11)
Board Scty, MTA
(3, 11)
Book Repairer
(9, 11)
Braillist
(3, 11)
Brd Comm Mbr, M=$200/Mtg
(23, 11)
Bricklayer
(14, 11)
Building Inspector
(170, 11)
Building Plans Engineer
(8, 11)
Building Services Technician
(4, 11)
CABLE SPLICER
(24, 11)
CAMP ASSISTANT
(59, 11)
CAPTAIN III (POLICE DEPARTMENT)
(37, 11)
CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC SAFE
(1, 11)
CAPTAIN, EMERGENCYCY MEDICAL SERVICES
(24, 11)
CAPTAIN, FIRE SUPPRESSION
(71, 11)
CAR AND AUTO PAINTER
(18, 11)
CARPENTER
(76, 11)
CARPENTER SUPERVISOR I
(11, 11)
CARPENTER SUPERVISOR II
(1, 11)
CASHIER I
(22, 11)
CASHIER II
(24, 11)
CASHIER III
(1, 11)
CEMENT FINISHER SUPERVISOR I
(3, 11)
CEMENT FINISHER SUPERVISOR II
(1, 11)
CEMENT MASON
(34, 11)
CENTRAL PROCESSING AND DISTRIBUTION TECHNICIAN
(30, 11)
CHEF
(5, 11)
CHEMIST I/II
(22, 11)
CHEMIST III
(6, 11)
CHIEF ADULT PROBATION OFFICER
(2, 11)
CHIEF ATTORNEY I (CIVIL & CRIMINAL)
(5, 11)
CHIEF BUILDING INSPECTOR
(3, 11)
CHIEF CLERK
(15, 11)
CHIEF DEPUTY ADULT PROBATION OFFICER
(2, 11)
CHIEF DEPUTY SHERIFF
(3, 11)
CHIEF DIETITIAN
(2, 11)
CHIEF DISTRICT ATTORNEY'S INVESTIGATOR
(1, 11)
CHIEF ELECTRICAL INSPECTOR
(1, 11)
CHIEF FIRE ALARM DISPATCHER
(1, 11)
CHIEF HOUSING INSPECTOR
(1, 11)
CHIEF MICROBIOLOGIST
(1, 11)
CHIEF NURSERY SPECIALIST
(1, 11)
CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
(1, 11)
CHIEF OF POLICE
(1, 11)
CHIEF PAYROLL AND PERSONNEL CLERK
(4, 11)
CHIEF PLUMBING INSPECTOR
(1, 11)
CHIEF PREPARATOR
(2, 11)
CHIEF PROBATION OFFICER, JUVENILE COURT
(1, 11)
CHIEF STATIONARY ENGINEER
(15, 11)
CHIEF STATIONARY ENGINEER, SEWAGE PLANT
(22, 11)
CHIEF STATIONARY ENGINEER, WATER TREATMENT PLANT
(5, 11)
CHIEF SURVEYOR
(6, 11)
CHIEF TELEPHONE OPERATOR
(1, 11)
CHIEF VICTIM/WITNESS INVESTIGATOR
(1, 11)
CHIEF WATER SERVICE INSPECTOR
(3, 11)
CHILD CARE SPECIALIST
(6, 11)
CHILD SUPPORT OFFICER II
(59, 11)
CHILD SUPPORT OFFICER III
(17, 11)
CITIZENS COMPLAINT OFFICER
(11, 11)
CITY ATTORNEY
(1, 11)
CITY PLANNING GRAPHICS SUPERVISOR
(1, 11)
CITY PLANNING INTERN
(2, 11)
CITY SHOPS ASSISTANT SUPERINTENDENT
(2, 11)
CIVIL ENGINEERING ASSISTANT
(17, 11)
CIVIL ENGINEERING ASSOCIATE I
(39, 11)
CLAIMS ADJUSTER
(5, 11)
CLAIMS INVESTIGATOR
(7, 11)
CLAIMS INVESTIGATOR CITY ATTORNEYS OFFICE
(33, 11)
CLAIMS PROCESS CLERK
(2, 11)
CLERK
(219, 11)
CLERK TYPIST
(135, 11)
CLINICAL NURSE SPECIALIST
(27, 11)
CLINICAL PHARMACIST
(33, 11)
CLINICAL PSYCHOLOGIST
(52, 11)
COLLECTIONS OFFICER
(3, 11)
COMMANDER III, (POLICE DEPARTMENT)
(7, 11)
COMMERCIAL DIVISION ASSISTANT SUPERVISOR
(16, 11)
COMMISSIONER
(46, 11)
COMMUNICATION LINE SUPERVISOR I
(2, 11)
COMMUNICATIONS DIRECTOR
(1, 11)
COMMUNICATIONS DISPATCHER I
(29, 11)
COMMUNICATIONS DISPATCHER II
(33, 11)
COMMUNICATIONS LINE WORKER SUPERVISOR II
(2, 11)
COMMUNICATIONS SYSTEMS TECHNICIAN
(23, 11)
COMMUNITY DEVELOPMENT ASSISTANT
(9, 11)
COMMUNITY DEVELOPMENT SPECIALIST
(22, 11)
CONFIDENTIAL CHIEF ATTORNEY II (CIVIL & CRIMINAL)
(3, 11)
CONFIDENTIAL SECRETARY CITY ATTORNEY
(1, 11)
CONFIDENTIAL SECRETARY TO DISTRICT ATTORNEY
(1, 11)
CONSERVATORSHIP/CASE MGNT SUPV
(1, 11)
CONSTRUCTION INSPECTOR
(60, 11)
CONTRACT COMPLIANCE OFFICER I
(33, 11)
CONTRACT COMPLIANCE OFFICER II
(16, 11)
COOK
(34, 11)
COORDINATOR OF CITIZEN INVOLVEMENT
(9, 11)
COORDINATOR, HUMAN RIGHTS COMMISSION
(3, 11)
COUNSELOR II
(3, 11)
COUNSELOR, FAMILY COURT SERVICE
(9, 11)
COUNSELOR, JUVENILE HALL
(144, 11)
COUNSELOR, LOG CABIN RANCH
(28, 11)
COURT AD RESOLUTION COORDINATOR
(1, 11)
COURT ADMINISTRATIVE SECRETARY
(1, 11)
COURT ADMINISTRATOR
(3, 11)
COURT ALTERNATIVE SPECIALIST I
(4, 11)
COURT ASSISTANT - SENIOR, SUPERIOR COURT
(8, 11)
COURT ASSISTANT, SUPERIOR COURT
(1, 11)
COURT CLERK
(1, 11)
COURT COMMISSIONER
(10, 11)
COURT COMPUTER APPLICATIONS ANALYST
(3, 11)
COURT COMPUTER APPLICATIONS PROGRAMMER
(3, 11)
COURT COMPUTER FACILITIES COORDINATOR
(1, 11)
COURT COMPUTER SYSTEMS ENGINEER II
(4, 11)
COURT COMPUTER SYSTEMS MANAGER
(3, 11)
COURT EXECUTIVE OFFICER
(1, 11)
COURT INTERPRETER
(17, 11)
COURT INTERPRETER SUPERVISOR
(1, 11)
COURT INVESTIGATOR
(8, 11)
COURT MANAGER
(13, 11)
COURT PARALEGAL
(1, 11)
COURT REPORTER
(62, 11)
COURT REPORTER COORDINATOR
(1, 11)
COURT STAFF ATTORNEY II
(12, 11)
COURT SUPERVISOR I
(1, 11)
COURT SUPERVISOR II
(17, 11)
COURT TRAINING SPECIALIST
(5, 11)
CRAFTS INSTRUCTOR
(9, 11)
CRANE MECHANIC SUPERVISOR
(1, 11)
CRIME LABORATORY MANAGER
(1, 11)
CRIMINAL JUSTICE SPECIALIST II
(7, 11)
CRIMINALIST I
(3, 11)
CRIMINALIST II
(18, 11)
CRIMINALIST III
(4, 11)
CURATOR I
(4, 11)
CURATOR II
(10, 11)
CURATOR III
(7, 11)
CURATOR IV
(6, 11)
CUSTODIAL ASSISTANT SUPERVISOR
(51, 11)
CUSTODIAL SUPERVISOR
(11, 11)
CUSTODIAN
(796, 11)
CUSTOMER SERVICE AGENT SUPERVISOR
(7, 11)
CUSTOMER SERVICE AGENT TRAINEE
(5, 11)
Cable Splicer
(62, 11)
Camp Assistant
(149, 11)
Capt,Fire Prev or Fire Invsgtn
(14, 11)
Captain 3
(101, 11)
Captain, (Fire Department)
(1, 11)
Captain, Emergency Med Svcs
(75, 11)
Captain, Fire Suppression
(211, 11)
Car and Auto Painter
(51, 11)
Carpenter
(226, 11)
Carpenter Supervisor 1
(29, 11)
Carpenter Supervisor 2
(5, 11)
Cashier 1
(56, 11)
Cashier 2
(75, 11)
Cashier 3
(1, 11)
Cement Finisher Supervisor 1
(12, 11)
Cement Finisher Supervisor 2
(2, 11)
Cement Mason
(111, 11)
Central Processing & Dist Tech
(88, 11)
Cfdntal Chf Atty 2,(Cvl&Crmnl)
(9, 11)
Cfdntal Sctry to City Atty
(3, 11)
Cfdntal Sctry to Distric Atty
(1, 11)
Chef
(16, 11)
Chemist
(21, 11)
Chemist I/II
(45, 11)
Chemist III
(18, 11)
Chf District Atty Investigator
(4, 11)
Chf Payroll & Personnel Clerk
(12, 11)
Chf Prob Ofc, Juv Court
(4, 11)
Chf Stationary Eng, Sew Plant
(52, 11)
Chf Statnry Eng,WtrTreat Plnt
(17, 11)
Chf Victim/Witness Invstgtor
(3, 11)
Chief Adult Probation Officer
(3, 11)
Chief Atty1 (Civil & Criminal)
(14, 11)
Chief Building Inspector
(12, 11)
Chief Clerk
(45, 11)
Chief Dep Adlt Prob Of (SFERS)
(3, 11)
Chief Deputy Adlt Probation Of
(4, 11)
Chief Deputy Sheriff
(10, 11)
Chief Dietitian
(5, 11)
Chief Electrical Inspector
(3, 11)
Chief Fire Alarm Dispatcher
(3, 11)
Chief Forensic Toxicologist
(1, 11)
Chief Housing Inspector
(3, 11)
Chief Investment Officer
(1, 11)
Chief Nursery Specialist
(3, 11)
Chief Plumbing Inspector
(3, 11)
Chief Preparator
(5, 11)
Chief Stationary Engineer
(43, 11)
Chief Surveyor
(19, 11)
Chief Telephone Operator
(3, 11)
Chief Water Service Inspector
(9, 11)
Chief of Police
(3, 11)
Chief, Fire Department
(3, 11)
Child Care Specialist
(17, 11)
Child Support Officer I
(8, 11)
Child Support Officer II
(167, 11)
Child Support Officer III
(33, 11)
Citizens Complaint Officer
(34, 11)
City Attorney
(3, 11)
City Planning Intern
(26, 11)
City Shops Asst Superintendent
(2, 11)
Civil Case Settlmnt Specialist
(1, 11)
Claims Adjuster
(17, 11)
Claims Investigator
(20, 11)
Claims Investigator, CA
(92, 11)
Claims Process Clerk
(4, 11)
Clerk
(764, 11)
Clerk Typist
(352, 11)
Clinical Nurse Specialist
(68, 11)
Clinical Pharmacist
(138, 11)
Clinical Psychologist
(149, 11)
Collection Supervisor
(6, 11)
Collections Officer
(9, 11)
Comm Pol Svcs Aide Supervisor
(24, 11)
Commander 3
(18, 11)
Commercial Div Asst Sprv
(49, 11)
Commissioner 16.700c, No Pay
(50, 11)
Commissioner No Benefits
(134, 11)
Communication Line Sprv1
(10, 11)
Communications Director
(2, 11)
Communications Dispatcher 1
(106, 11)
Communications Dispatcher 2
(88, 11)
Communications Line Wrk Sprv 2
(6, 11)
Communications Systems Tech
(70, 11)
Community Development Asst
(23, 11)
Community Development Spec
(56, 11)
Community Police Services Aide
(559, 11)
Conservatorship/Case Mgt Sprv
(3, 11)
Construction Inspector
(192, 11)
Contract Compliance Officer 1
(96, 11)
Contract Compliance Officer 2
(48, 11)
Controller
(3, 11)
Conversion
(1, 11)
Cook
(96, 11)
Coord of Citizen Involvement
(24, 11)
Coord, Human Rights Comm
(12, 11)
Counselor 2
(8, 11)
Counselor, Family Court Svc
(15, 11)
Counselor, Juvenile Hall
(319, 11)
Counselor, Juvenile Hall SFERS
(54, 11)
Counselor, Log Cabin Ranch
(63, 11)
Counselor,Log Cabin Rnch SFERS
(16, 11)
Court Administrative Secretary
(4, 11)
Court Administrator
(4, 11)
Court Alternative Specialist 1
(10, 11)
Court Asst-Sr, Superior Court
(3, 11)
Court Asst., Superior Court
(2, 11)
Court Clerk
(3, 11)
Court Commissioner
(8, 11)
Court Computer Sys Manager
(6, 11)
Court Executive Officer
(2, 11)
Court Interpreter
(33, 11)
Court Interpreter Supervisor
(2, 11)
Court Invstgtor, Superior Crt
(12, 11)
Court Manager
(16, 11)
Court Paralegal
(6, 11)
Court Reporter
(105, 11)
Court Reporter Coordinator
(2, 11)
Court Staff Attorney II
(20, 11)
Court Supervisor I
(1, 11)
Court Supervisor II
(40, 11)
Court Training Specialist
(7, 11)
Crafts Instructor
(26, 11)
Crane Mechanic Supervisor
(3, 11)
Crime Lab Mgr
(2, 11)
Criminal Justice Specialist 2
(18, 11)
Criminalist I
(9, 11)
Criminalist II
(46, 11)
Criminalist III
(13, 11)
Ct Comp App Analyst
(4, 11)
Ct Comp App Programmer
(6, 11)
Ct Comp Facilities Coord
(4, 11)
Ct Comp Sys Engineer II
(7, 11)
Curator 1
(10, 11)
Curator 2
(25, 11)
Curator 3
(20, 11)
Curator 4
(15, 11)
Custodial Assistant Supervisor
(164, 11)
Custodial Supervisor
(32, 11)
Custodian
(2418, 11)
Customer Service Agent
(206, 11)
Customer Service Agent Supv
(22, 11)
Customer Service Agent Trainee
(33, 11)
DA Investigative Assist
(96, 11)
DENTAL AIDE
(18, 11)
DENTAL HYGIENIST
(5, 11)
DENTIST
(19, 11)
DEPARTMENT HEAD I
(12, 11)
DEPARTMENT HEAD II
(7, 11)
DEPARTMENT HEAD III
(8, 11)
DEPARTMENT HEAD IV
(4, 11)
DEPARTMENT HEAD V
(7, 11)
DEPUTY CHIEF III (POLICE DEPARTMENT)
(5, 11)
DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
(3, 11)
DEPUTY COURT CLERK I
(2, 11)
DEPUTY COURT CLERK II
(162, 11)
DEPUTY COURT CLERK III
(104, 11)
DEPUTY DIRECTOR I
(6, 11)
DEPUTY DIRECTOR I - MUNICIPAL TRANSPORTATION AGE
(5, 11)
DEPUTY DIRECTOR II
(32, 11)
DEPUTY DIRECTOR II - MUNICIPAL TRANSPORTATION AG
(5, 11)
DEPUTY DIRECTOR III
(27, 11)
DEPUTY DIRECTOR IV
(23, 11)
DEPUTY DIRECTOR OF INVESTMENTS
(1, 11)
DEPUTY DIRECTOR V
(16, 11)
DEPUTY PROBATION OFFICER
(136, 11)
DEPUTY SEALER OF WEIGHTS AND MEASURES
(1, 11)
DEPUTY SHERIFF
(685, 11)
DIAGNOSTIC IMAGING TECH I
(35, 11)
DIAGNOSTIC IMAGING TECH II
(28, 11)
DIAGNOSTIC IMAGING TECH III
(10, 11)
DIAGNOSTIC IMAGING TECH IV
(6, 11)

In [219]:
df.isin([335279.91])

        EmployeeName  JobTitle  BasePay  OvertimePay  ...  TotalPayBenefits   Year  Fire_department_Ename  Department
0              False     False    False        False  ...             False  False                  False       False
1              False     False    False        False  ...             False  False                  False       False
2              False     False    False        False  ...              True  False                  False       False
3              False     False    False        False  ...             False  False                  False       False
4              False     False    False        False  ...             False  False                  False       False
...              ...       ...      ...          ...  ...               ...    ...                    ...         ...
148649         False     False    False        False  ...             False  False                  False       False
148650         False     False    False        False  ...             False  False                  False       False
148651         False     False    False        False  ...             False  False                  False       False
148652         False     False    False        False  ...             False  False                  False       False
148653         False     False    False        False  ...             False  False                  False       False

[148654 rows x 11 columns]

In [222]:
r=(df==5).any().any()

In [223]:
r

True

#### search for unique value in full data frame and display matching rows

In [228]:
df[df.eq('DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)').any(axis=1)]

       EmployeeName  ...                                       Department
4   PATRICK GARDNER  ...  [DEPUTY CHIEF OF DEPARTMENT,, FIRE DEPARTMENT)]
29    MONICA FIELDS  ...  [DEPUTY CHIEF OF DEPARTMENT,, FIRE DEPARTMENT)]
42  THOMAS SIRAGUSA  ...  [DEPUTY CHIEF OF DEPARTMENT,, FIRE DEPARTMENT)]

[3 rows x 11 columns]